# Generated by Django 3.0.2 on 2020-01-17 19:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Queued'), (2, 'Processed'), (3, 'Concilited'), (4, 'Canceled'), (5, 'refund')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50),
        ),
    ]
