# Generated by Django 3.0.2 on 2020-01-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20200117_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Queued'), (2, 'Processed'), (3, 'Concilited'), (4, 'Canceled'), (5, 'Refunded')]),
        ),
    ]
